/**
 * Доменные коды ошибок. Клиент ветвится по коду, а не по тексту.
 * Общие транспортные коды лежат в `ErrorCode` (api-error.ts).
 */
export const AuthErrorCode = {
  SMS_RATE_LIMITED: 'SMS_RATE_LIMITED',
  CODE_INVALID: 'CODE_INVALID',
  CODE_EXPIRED: 'CODE_EXPIRED',
  CODE_ATTEMPTS_EXCEEDED: 'CODE_ATTEMPTS_EXCEEDED',
  REFRESH_INVALID: 'REFRESH_INVALID',
  USER_BLOCKED: 'USER_BLOCKED',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',
} as const;

export const BoxErrorCode = {
  BEST_BEFORE_TOO_EARLY: 'BEST_BEFORE_TOO_EARLY',
  PICKUP_WINDOW_INVALID: 'PICKUP_WINDOW_INVALID',
  PRICE_ABOVE_ORIGINAL: 'PRICE_ABOVE_ORIGINAL',
  BOX_NOT_ACTIVE: 'BOX_NOT_ACTIVE',
  NOT_ENOUGH_QUANTITY: 'NOT_ENOUGH_QUANTITY',
  RECURRENCE_RULE_REQUIRED: 'RECURRENCE_RULE_REQUIRED',
} as const;

export const OrderErrorCode = {
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  CANCELLATION_WINDOW_PASSED: 'CANCELLATION_WINDOW_PASSED',
  PICKUP_CODE_UNKNOWN: 'PICKUP_CODE_UNKNOWN',
  ORDER_ALREADY_COLLECTED: 'ORDER_ALREADY_COLLECTED',
  PICKUP_WINDOW_NOT_OPEN: 'PICKUP_WINDOW_NOT_OPEN',
} as const;

export const MerchantErrorCode = {
  MERCHANT_NOT_APPROVED: 'MERCHANT_NOT_APPROVED',
  MERCHANT_ALREADY_EXISTS: 'MERCHANT_ALREADY_EXISTS',
  NOT_MERCHANT_OWNER: 'NOT_MERCHANT_OWNER',
} as const;
